### ISSUE TITLE
[SUPPORT] Not showing eye when pressing alt key

### ISSUE THREAD

**Issue by Sotamies2** [qbcore-framework/qb-target#124]
Just not working for me. I have newest version of qb-core and it should work.

**Comment by Sotamies2** [comment]
Yea

**Comment by BerkieBb** [comment]
Did you make any changes to qb-target like adding something to the config?

**Comment by Sotamies2** [comment]
Nope just installed it

**Comment by BerkieBb** [comment]
And did it start after qb-core?

**Comment by Sotamies2** [comment]
Yep it did

**Comment by Sotamies2** [comment]
I just made new server all files are like 3days old i dowloaded newest scripts

**Comment by BerkieBb** [comment]
Restart your server but before you do that, take qb-target out of the server.cfg

**Comment by BerkieBb** [comment]
Then start qb-target manually when you're loaded in

**Comment by Sotamies2** [comment]
and not working

**Comment by BerkieBb** [comment]
Could you restart qb-target manually now and show me a screenshot of what pops up in F8?

**Comment by Sotamies2** [comment]
![image](https://user-images.githubusercontent.com/104374694/165120445-e17eccac-0ef3-4c52-b866-4ed1ca550d7f.png)
No errors in game console and server console

**Comment by Sotamies2** [comment]
If you can come to discord call i can show you everything and its easier to solve problem

**Comment by Sotamies2** [comment]
I just have done my server again and dont work
i have putted oxmysql, qb-core, PolyZone and qb-target

**Comment by BerkieBb** [comment]
Please head to the qbcore discord to get more support on this, https://discord.gg/qbcore
