### ISSUE TITLE
Left ALT does not work for me [SUPPORT]

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-target#131]
**Problem:**
Left ALT does not work for me and its LMENU on config file but i open with f11

**Comment by BerkieBb** [comment]
What layout is your keyboard in?

**Comment by BerkieBb** [comment]
Your keybind is set in your settings, press Escape, then go to Key Bindings and then to the FiveM tab

**Comment by OxGhali** [comment]
okay so u mean i have to set it on fivem keybind thank u very much i didn't think of it xd
