### ISSUE TITLE
[SUPPORT] Error

### ISSUE THREAD

**Issue by Sotamies2** [qbcore-framework/qb-target#135]
![image](https://user-images.githubusercontent.com/104374694/170030006-1e35b4aa-ba9b-41ab-afab-aa8d35e45ae5.png)

Can somebody help with this?

**Comment by BerkieBb** [comment]
Make sure qb-target starts before all other resources but after qb-core

**Comment by Sotamies2** [comment]
> Make sure qb-target starts before all other resources but after qb-core

Worked
