### ISSUE TITLE
[BUG] AddBoxZone with Sprites not working correctly

### ISSUE THREAD

**Issue by keeganwut** [qbcore-framework/qb-target#138]
**Describe the bug**
If you have sprites enabled, and try to interact with a boxzone export it highlights and draws the sprite but does not let you interact.
Unsure if my export is outdated or what, I'm merging from a very old qb-target to a newer.

But I did manually merge the sprite update and it still gave me the same issue.

So, I think it is an issue with sprites rather than the export.

**To Reproduce**
1. Go to any script and use the AddBoxZone export
2. Enable sprites in qb-target config
3. Press your eye key
4. Try to interact with the box zone (it shows but does not do anything when you click)

**Expected behavior**
To show the sprite and allow you to interact with box zone.

**Screenshots**
![image](https://user-images.githubusercontent.com/63989752/173206578-5acc8ca8-fc63-4cec-a585-b8e4e238f39b.png)
![image](https://user-images.githubusercontent.com/63989752/173206559-f8c1f191-df9d-4f38-96be-f1f185cea0a6.png)

**Additional context**
None

**Comment by BerkieBb** [comment]
Can you share the options for the boxzons that you have, I'l try those out and see if I can reproduce it using that

**Comment by PeeganKreece** [comment]
Beware this might be slightly outdated, haven't really compared to the latest version of the export. Change the table coords to a standard xyz. I also had a caninteract function in here, I removed it just to save you time but it might also be a variable highly doubt though.

           exports['qb-target']:AddBoxZone(Config.Safes[k].camId, vector3(Config.Safes[k][1].x, Config.Safes[k][1].y, Config.Safes[k][1].z - 0.5), 0.8, 0.8, {
                name = Config.Safes[k].camId,
                heading = Config.Safes[k][1].w,
                minZ = Config.Safes[k][1].z-1.0,
                maxZ = Config.Safes[k][1].z,
            }, {
            options = {
                {
                    type = "client",
                    event = "hacking_usb:use",
                    icon = 'fas fa-user-secret',
                    label = 'Crack Safe',
                },
                {
                    type = "client",
                    event = "safe:reward",
                    icon = 'fas fa-box-open',
                    label = 'Open Safe',
                },
            },
                distance = 1.0,
            })

**Comment by darkets** [comment]
Issue is still present.

**Comment by SodaPortal** [comment]
Having the same issue with DrawSprite enabled and trying to interact with a BoxZone target.

**Comment by liquidadrenalin** [comment]
Currently using latest version and can confirm we are also experiencing the same issue at the moment.

**Comment by abdel1touimi** [comment]
the issue comes from using integer as target name (it should be string) :
```
name = Config.Safes[k].camId
```

**Comment by WEEZOOKARP** [comment]
even after converting everything in the name section to a string using tostring() it comes up with the error
![image](https://github.com/qbcore-framework/qb-target/assets/76672483/c4551351-3e43-4ca6-8593-45590d9d5cc3)
![image](https://github.com/qbcore-framework/qb-target/assets/76672483/599a6796-39d2-44bb-8832-b9450ffee961)
![image](https://github.com/qbcore-framework/qb-target/assets/76672483/f48e6fc0-d3bc-46a4-9c78-de968cad6e0d)
