### ISSUE TITLE
[BUG] Target not working for female characters

### ISSUE THREAD

**Issue by JonasDev99** [qbcore-framework/qb-target#144]
Certain targets don't work for female characters.

This target:
![image](https://user-images.githubusercontent.com/25738474/178157268-284e952e-93f8-4485-a1eb-a9bd109accea.png)

With the model: prop_ind_mech_01c

The target won't show up for female characters, only for male ones.

**Comment by BerkieBb** [comment]
You don't target players by model

**Comment by JonasDev99** [comment]
I am saying that the target model prop_ind_mech_01c cannot be targeted by female characters on my server. Initially I thought it was random but then I created a character and tried to target the prop_ind_mech_01c and the eye didn't change color.

**Comment by BerkieBb** [comment]
That's very weird as the target doesn't look at your character at all, it even ignores it

**Comment by JonasDev99** [comment]
Ah let me check my script maybe the target is not being created in the first place...

**Comment by JonasDev99** [comment]
Ok, so I placed a print before and after and that worked. So Idk why it would not work for female characters... but its only some of the targets.

**Comment by JonasDev99** [comment]
Nevermind, I think it is related to something else on my end...
