### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by EpicFireR6** [qbcore-framework/qb-target#145]
**Problem:**
While cuffed, dead, or in last stand. You can still third eye and for example steal shoes and take hostage.

**Wanted Outcome:**
Disable qb-target while cuffed, dead or in last stand

**Current Point:**
I've tried putting DisableControlAction(0, 19, true) in the policejob/client/interactions and it's still not working. Noe bugs, errors or anything

**Comment by BerkieBb** [comment]
Just use the AllowTargeting export to disable qb-target for the current client

**Comment by BerkieBb** [comment]
qb-target uses keymapping so you can't disable it's controls
