### ISSUE TITLE
[BUG] DrawSprite Issue

### ISSUE THREAD

**Issue by ansljeremy** [qbcore-framework/qb-target#148]
**Describe the bug**
Config.DrawSprite shows the Sprite for all targets even if you do not have permission to use it (incorrect job or item).

**To Reproduce**
1. Enable Config.DrawSprite
2. Job lock a target

**Expected behavior**
Config.DrawSprite should not show Sprites if you cannot access it

**Comment by BerkieBb** [comment]
That's because DrawSprite can't check it yet, the system is written in such a way that it does the check only when a polyzone is selected alreqdy, can't do it outside of it
