### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by aboshaheen553** [qbcore-framework/qb-target#150]
I need to lock it when I'm dead

**Comment by tom-osborne** [comment]
Sorry, you're going to have to write a bit more than that for anybody to understand what you require support for. Please could you elaborate?

**Comment by aboshaheen553** [comment]
When it's dead inside the server, I can use the alt button. I want to turn off the alt button when I'm dead

**Comment by BerkieBb** [comment]
Read the TEMPLATES.md on `AllowTargeting`

**Comment by aboshaheen553** [comment]
Use the code on the server.lua

**Comment by BerkieBb** [comment]
qb-target is client side only

**Comment by tom-osborne** [comment]
> When it's dead inside the server, I can use the alt button. I want to turn off the alt button when I'm dead

See here: https://github.com/qbcore-framework/qb-target/issues/145#issuecomment-1186125652
