### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by TheIvan2022** [qbcore-framework/qb-target#151]
**Problem:**
The target does not work for me with the current version, IF alt is pressed there is nothing on the screen

**Wanted Outcome:**
See if you could help

**Current Point:**
I had it working once but suddenly stopeed working

**Screenshots:**
I Don't know here con a screenshot could help

**Additional context:**
I have been dealing with this ussed for a long time now so i use and older version that does not work very well

**Comment by NevoSwissa** [comment]
i have the same issue, older versions work just fine but it seems that its not fixed yet.

**Comment by Archangelza1** [comment]
Hi @TheIvan2022 please could you elaborate your issue further. If you are still struggling feel free to add me on discord and I can join and have a look: Archangel_za#4005

**Comment by RPShaggy** [comment]
I have this exact same issue, someone pls help!
