### ISSUE TITLE
[SUPPORT-NEEDED]

### ISSUE THREAD

**Issue by IIP1AX** [qbcore-framework/qb-target#153]
**Problem:**
remove target dose not work with me

**Wanted Outcome:**
i want to remove a target model from an animal after harvest it so it's not working with me

**Current Point:**
local model = GetEntityModel(ped)
local animal = getAnimalMatch(model)
exports['qb-target']:RemoveTargetModel(animal, "test")

**Screenshots:**
If applicable, add screenshots to help explain your problem

**Additional context:**
it does add the target on the entitymodel but in remove target it does not remove the target and there is no error

**Comment by BerkieBb** [comment]
Can you show your original options that you're trying to remove

**Comment by IIP1AX** [comment]
> Can you show your original options that you're trying to remove

    exports['qb-target']:AddTargetModel(animal, {
        options = {
            {
                event = "ipx-hunting:client:animalharve",
                icon = "fas fa-circle",
                label = "harvest",
                dis = distancePedPlayer,
                ped = ped,
                i = i,
            },
        },
        distance = 2.5,
    })

**Comment by BerkieBb** [comment]
The second argument of RemoveTargetModel is the label of the option you want to remove

**Comment by IIP1AX** [comment]
> Can you show your original options that you're trying to remove



> The second argument of RemoveTargetModel is the label of the option you want to remove

i did try this before it didn't work but it did now okay thxxx
