### ISSUE TITLE
[SUPPORT] Target not working for some props, with multiple scripts

### ISSUE THREAD

**Issue by Swahgner** [qbcore-framework/qb-target#156]
**Problem:**
Tried using ps-drugprocessing, and ps-signrobbery, in drugprocessing only cocaine field will not work, in signrobbery, none of the props is targetable (I have tried replacing a prop for the sign with a shopping cart, which works)

**Wanted Outcome:**
Show the eye

**Current Point:**
I figure it is a qb-target issue, since the same issue happens on multiple scripts. I thought it was a problem with custom models, but signrobbery uses standard props, which does not work.

**Screenshots:**
From ps-signrobbery
![billede](https://user-images.githubusercontent.com/7695271/187008044-0c998360-1666-4346-928c-1a273059f473.png)

From ps-drugprocessing
![billede](https://user-images.githubusercontent.com/7695271/187008065-476a08e0-b689-4ce8-acc7-37fb3175d031.png)

**Additional context:**
[EDIT]
Just tried changing the model in ps-signrobbery of one of the signs to a trolley, as you can see, it works with that model
```lua
-- Original code
    exports['qb-target']:AddTargetModel('prop_sign_road_02a', {
        options = {
            {
                type = 'client',
                event = "qb-signrobbery:client:YieldSign",
                icon = 'fas fa-user-secret',
                label = 'Steal Sign',
            }
        },
        distance = 4.0, 
    })
```

```lua
    -- Altered to trolley
    exports['qb-target']:AddTargetModel("prop_skid_trolley_2", {
        options = {
            {
                type = "client",
                event = "qb-signrobbery:client:DontBlockIntersectionSign",
                icon = "fas fa-user-secret",
                label = "Steal Sign",
            }
        },
        distance = 4.0, 
    })
```

![billede](https://user-images.githubusercontent.com/7695271/187008544-230693ba-8f37-4202-b559-c0de76834e87.png)

**Comment by singh-manavv** [comment]
The prop id you have entered for the road sign is wrong , it works , always make sure the prop id correct!
![image](https://user-images.githubusercontent.com/55807344/187009047-92b0336f-06cc-45ad-b573-155e2f07cc7e.png)

**Comment by singh-manavv** [comment]
![image](https://user-images.githubusercontent.com/55807344/187009096-db501040-fa67-4015-871b-b59f180760a7.png)

**Comment by singh-manavv** [comment]
> **Problem:** Tried using ps-drugprocessing, and ps-signrobbery, in drugprocessing only cocaine field will not work, in signrobbery, none of the props is targetable (I have tried replacing a prop for the sign with a shopping cart, which works)
> 
> **Wanted Outcome:** Show the eye
> 
> **Current Point:** I figure it is a qb-target issue, since the same issue happens on multiple scripts. I thought it was a problem with custom models, but signrobbery uses standard props, which does not work.
> 
> **Screenshots:** From ps-signrobbery ![billede](https://user-images.githubusercontent.com/7695271/187008044-0c998360-1666-4346-928c-1a273059f473.png)
> 
> From ps-drugprocessing ![billede](https://user-images.githubusercontent.com/7695271/187008065-476a08e0-b689-4ce8-acc7-37fb3175d031.png)
> 
> **Additional context:** [EDIT] Just tried changing the model in ps-signrobbery of one of the signs to a trolley, as you can see, it works with that model
> 
> ```lua
> -- Original code
>     exports['qb-target']:AddTargetModel('prop_sign_road_02a', {
>         options = {
>             {
>                 type = 'client',
>                 event = "qb-signrobbery:client:YieldSign",
>                 icon = 'fas fa-user-secret',
>                 label = 'Steal Sign',
>             }
>         },
>         distance = 4.0, 
>     })
> ```
> 
> ```lua
>     -- Altered to trolley
>     exports['qb-target']:AddTargetModel("prop_skid_trolley_2", {
>         options = {
>             {
>                 type = "client",
>                 event = "qb-signrobbery:client:DontBlockIntersectionSign",
>                 icon = "fas fa-user-secret",
>                 label = "Steal Sign",
>             }
>         },
>         distance = 4.0, 
>     })
> ```
> 
> ![billede](https://user-images.githubusercontent.com/7695271/187008544-230693ba-8f37-4202-b559-c0de76834e87.png)

Use this website for getting correct prop IDs - https://gta-objects.xyz/

**Comment by Swahgner** [comment]
> The prop id you have entered for the road sign is wrong , it works , always make sure the prop id correct! ![image](https://user-images.githubusercontent.com/55807344/187009047-92b0336f-06cc-45ad-b573-155e2f07cc7e.png)

Can you tell me what the correct id is then? I just used the link you sent me, and this is what I found:
![billede](https://user-images.githubusercontent.com/7695271/187024853-db5b2746-7eb1-466c-a786-abbc2f71d3f4.png)

This is my code:
```lua
    exports['qb-target']:AddTargetModel('prop_sign_road_02a', {
        options = {
            {
                type = 'client',
                event = "qb-signrobbery:client:YieldSign",
                icon = 'fas fa-user-secret',
                label = 'Steal Sign',
            }
        },
        distance = 4.0, 
    })
```

As far as I can see, those are identical?

**Comment by Swahgner** [comment]
I just tried with this code:

```lua
    exports['qb-target']:AddTargetModel('prop_sign_road_03e', {
        options = {
            {
                type = 'client',
                event = "qb-signrobbery:client:testing",
                icon = 'fas fa-user-secret',
                label = 'X it!',
            }
        },
        distance = 4.0, 
    })
    exports['qb-target']:AddTargetModel('prop_skid_trolley_2', {
        options = {
            {
                type = 'client',
                event = "qb-signrobbery:client:testing",
                icon = 'fas fa-user-secret',
                label = 'X it!',
            }
        },
        distance = 4.0, 
    })
    exports['qb-target']:AddTargetModel('prop_rub_couch01', {
        options = {
            {
                type = 'client',
                event = "qb-signrobbery:client:testing",
                icon = 'fas fa-user-secret',
                label = 'X it!',
            }
        },
        distance = 4.0, 
    })
```
(The event is simply just printing a debug message to determine if it will run)

The first with the sign doesn't work, but the trolley and the couch works like a charm

**Comment by singh-manavv** [comment]
> I just tried with this code:
> 
> ```lua
>     exports['qb-target']:AddTargetModel('prop_sign_road_03e', {
>         options = {
>             {
>                 type = 'client',
>                 event = "qb-signrobbery:client:testing",
>                 icon = 'fas fa-user-secret',
>                 label = 'X it!',
>             }
>         },
>         distance = 4.0, 
>     })
>     exports['qb-target']:AddTargetModel('prop_skid_trolley_2', {
>         options = {
>             {
>                 type = 'client',
>                 event = "qb-signrobbery:client:testing",
>                 icon = 'fas fa-user-secret',
>                 label = 'X it!',
>             }
>         },
>         distance = 4.0, 
>     })
>     exports['qb-target']:AddTargetModel('prop_rub_couch01', {
>         options = {
>             {
>                 type = 'client',
>                 event = "qb-signrobbery:client:testing",
>                 icon = 'fas fa-user-secret',
>                 label = 'X it!',
>             }
>         },
>         distance = 4.0, 
>     })
> ```
> 
> (The event is simply just printing a debug message to determine if it will run)
> 
> The first with the sign doesn't work, but the trolley and the couch works like a charm

Seems to be working fine to me , please make sure you have the latest release of qb-target v5.3.9 from [the github](https://github.com/qbcore-framework/qb-target/releases/tag/5.3.9)
![Screenshot (587)](https://user-images.githubusercontent.com/55807344/187026781-43aee12b-642b-486f-bcc2-0b93ac5a63f6.png)
![Screenshot (588)](https://user-images.githubusercontent.com/55807344/187026783-3b75e9dd-7eb8-41cf-ad18-f4ae74afc131.png)
![dwadasdawdawdada](https://user-images.githubusercontent.com/55807344/187026810-a9ffc15b-b941-41eb-b9f7-d902cd2ffa5e.png)

**Comment by Swahgner** [comment]
> > I just tried with this code:
> > ```lua
> >     exports['qb-target']:AddTargetModel('prop_sign_road_03e', {
> >         options = {
> >             {
> >                 type = 'client',
> >                 event = "qb-signrobbery:client:testing",
> >                 icon = 'fas fa-user-secret',
> >                 label = 'X it!',
> >             }
> >         },
> >         distance = 4.0, 
> >     })
> >     exports['qb-target']:AddTargetModel('prop_skid_trolley_2', {
> >         options = {
> >             {
> >                 type = 'client',
> >                 event = "qb-signrobbery:client:testing",
> >                 icon = 'fas fa-user-secret',
> >                 label = 'X it!',
> >             }
> >         },
> >         distance = 4.0, 
> >     })
> >     exports['qb-target']:AddTargetModel('prop_rub_couch01', {
> >         options = {
> >             {
> >                 type = 'client',
> >                 event = "qb-signrobbery:client:testing",
> >                 icon = 'fas fa-user-secret',
> >                 label = 'X it!',
> >             }
> >         },
> >         distance = 4.0, 
> >     })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (The event is simply just printing a debug message to determine if it will run)
> > The first with the sign doesn't work, but the trolley and the couch works like a charm
> 
> Seems to be working fine to me , please make sure you have the latest release of qb-target v5.3.9 from [the github](https://github.com/qbcore-framework/qb-target/releases/tag/5.3.9) ![Screenshot (587)](https://user-images.githubusercontent.com/55807344/187026781-43aee12b-642b-486f-bcc2-0b93ac5a63f6.png) ![Screenshot (588)](https://user-images.githubusercontent.com/55807344/187026783-3b75e9dd-7eb8-41cf-ad18-f4ae74afc131.png) ![dwadasdawdawdada](https://user-images.githubusercontent.com/55807344/187026810-a9ffc15b-b941-41eb-b9f7-d902cd2ffa5e.png)

That did it!
I thought I had the latest version, but I must have downloaded a wrong one

Thank you for the help!
