### ISSUE TITLE
[BUG] AddTargetModel Weird Inconsistencies

### ISSUE THREAD

**Issue by EinS4ckZwiebeln** [qbcore-framework/qb-target#158]
**Describe the bug**
Export/Function `AddTargetModel` only works when the entity is created on the client side and afterwards set as no longer needed. (Networked & Scripthosted)

If done on the server side, the created entity does not work at all with `AddTargetModel`, even if it is perfectly networked and/or migrated to the client afterwards. Setting the ped as no longer need does not help either here.

Note: This behaviour was observed on the `a_c_deer` ped/model.

**To Reproduce**
1. Create an entity/ped on the client side using `CreatePed`
`local deer = CreatePed(28, "a_c_deer", coords.x, coords.y, coords.z + 0.25, math.random(1, 359) + .0, true, true)`

2. Observe that `AddTargetModel` does not seem to work

3. Add `SetPedAsNoLongerNeeded` below
`local deer = CreatePed(28, "a_c_deer", coords.x, coords.y, coords.z + 0.25, math.random(1, 359) + .0, true, true)`
`SetPedAsNoLongerNeeded(deer)`

5. Ensure that it in fact works now

6. Create the ped on the server side and pass it's netId to the client in order to set it as no longer needed
`local deer = CreatePed(28, "a_c_deer", coords.x, coords.y, coords.z + 0.25, math.random(1, 359) + .0, true, true)`
`TriggerClientEvent("example:event", source, NetworkGetNetworkIdFromEntity(deer))`

7. Notice that `AddTargetModel` is broken again and the model cannot be interacted with

**Expected behavior**
Consistency between entities/peds created by the server and the client regarding functionality of the `AddTargetModel` export.

**Additional context**
Tested on latest qb-core & qb-target. Entities/Peds spawned with vMenu seem to be broken as well.

**Comment by jnccloud** [comment]
@EinS4ckZwiebeln can you try my PR and see if it helps? Just a one letter edit #166
