### ISSUE TITLE
[BUG] exports['qb-target']:SpawnPed not working

### ISSUE THREAD

**Issue by SuelTheDev** [qbcore-framework/qb-target#161]
I'm trying to use the SpawnPed function export, but nothing happens, I've tested it with my own code and the example code that comes in the github and both nothing happens.

**To Reproduce**

1. I call this function in my client code.

 exports["qb-target"]:SpawnPed({
     model = `a_m_y_business_02`,
        coords = vector4(453.49, -608.09, 28.58, 264.58),
        freeze = true,
        invincible = true,
        blockevents = true,
        target = {
            useModel = false,
            options = {
                {
                    type = 'client',
                    event = "test",
                    label = "Entrar em serviço",
                    icon = "fas fa-example"
               }
            },
            distance = 2.5
        },
        action = function(spawndata)
             print("PED SPAWNED", spawndata)
        end
     })

**Expected behavior**

That the PED is created and the target functions are associated with it to make the interaction.

**Screenshots**

**Additional context**

**Comment by singh-manavv** [comment]
You need to put the ped model name inside` "a_m_y_business_02" or  'a_m_y_business_02'`

**Comment by SuelTheDev** [comment]
> You need to put the ped model name inside double or single inverted commas ` "a_m_y_business_02" or 'a_m_y_business_02'`

In the original code there are the "", must have happened during the copy and paste, but I just discovered that there is a spawnNow property, which is not in the documentation, at least not in my last query.
