### ISSUE TITLE
qb-target icon

### ISSUE THREAD

**Issue by Steviithetv** [qbcore-framework/qb-target#172]
**Problem:**
I have this problem with the eye and can't figure out what happened. This happens after I reinstall FiveM and only I have this problem and only in my server. 

**Wanted Outcome:**
I want the icon to show normally not like broken image.

**Current Point:**
This happened after I reinstall FiveM to delete all cache files and after joining again I can't see the icon of the eye.

**Screenshots:**

![image](https://user-images.githubusercontent.com/111495951/217663199-eda6d1ed-e996-438b-bc93-e58d8a7cbffb.png)

**Additional context:**
Others in the server see it normally like this 
![image](https://user-images.githubusercontent.com/111495951/217663371-c1104d46-c4ee-441d-ade1-76a0f9fa90f7.png)

**Comment by tom-osborne** [comment]
Make sure you have onesync enabled on your server

**Comment by Steviithetv** [comment]
I have enabled it and checked every single setting that can make problem even changed graphic settings to low and back to high, still the same.

**Comment by DNDdjay** [comment]
ant fix for it, for i have the same problem

**Comment by MrTeaRexx** [comment]
do we know if this is a framework issue cause im suffering the same thing with cache cleared and onesync enabled

**Comment by DNDdjay** [comment]
I needed to go over to ox_target instead

**Comment by MrTeaRexx** [comment]
> I needed to go over to ox_target instead

I found this, Try that right at the bottom of the post

**Comment by MrTeaRexx** [comment]
https://github.com/qbcore-framework/qb-target/issues/195
