### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by TamerWaves** [qbcore-framework/qb-target#173]
**Problem:**
Brand new server install and my qb target does nothing when your press L Alt

**Wanted Outcome:**
Help fixing

**Current Point:**
Zero errors popping up

**Screenshots:**
If applicable, add screenshots to help explain your problem

**Additional context:**
Add any other context about the problem here

**Comment by tom-osborne** [comment]
Ensure you have onesync turned on in txadmin.

**Comment by RPShaggy** [comment]
I have this same issue. Any fixes??

**Comment by tom-osborne** [comment]
> I have this same issue. Any fixes??

Enable onesync in txAdmin.

**Comment by RPShaggy** [comment]
This doesn't work. It's a fresh server so OneSync is automatically enabled.

**Comment by tom-osborne** [comment]
> This doesn't work. It's a fresh server so OneSync is automatically enabled.

Did you check?

**Comment by RPShaggy** [comment]
Yup, I have tried everything, gone through all of the same people having the same issues but there's no concrete solution. Even after wiping the VPS and reinstalling the fresh QBCore server (Linux VPS) I'm still having the same issue which is very confusing

**Comment by RPShaggy** [comment]
Also this happeneded out of nowhere after an automatic server restart with no changes which is why I'm so lost on this.
