### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by 604gamingfb** [qbcore-framework/qb-target#175]
**Problem:**
My server is the QB Core platform my issue is the qb-target eye isn’t working now. I switched VPS and did a full backup and now it does not function. Nothing was changed in the meta or anything. Any ideas how to fix?

**Wanted Outcome:**
Solution to fix issue.

**Current Point:**
All information about where you are now with your problem goes here

**Screenshots:**
If applicable, add screenshots to help explain your problem

**Additional context:**
Add any other context about the problem here

**Comment by RPShaggy** [comment]
Hey how did you fix this?

**Comment by 604gamingfb** [comment]
> Hey how did you fix this?

You go into your server dashboard go to settings and turn your OneSync on and then reboot your server. That’s the fix!

**Comment by 604gamingfb** [comment]
![840D05F3-1A63-42AE-8E5B-949892AD21EF](https://user-images.githubusercontent.com/89455013/228586236-d88ac8b2-18b8-4716-8e04-a1d10ed35749.jpeg)

**Comment by RPShaggy** [comment]
Thanks for a quick response. I already have it on with infinity :/
