### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by skullcrazy007** [qbcore-framework/qb-target#177]
I have a problem with tafget.
Namely, I use an older version of the target that has config.lua and inside are the coordinates of the target that I use in the shop... I bought some new scripts that don't work on that old target, but look for a new one.
now I have a question, what would be the easiest way to update the new target so that I can set these things from config.lu?

**Comment by tom-osborne** [comment]
Replace the resource with the new one, copy across any config changes you made. Make sure those changes are in the correct format for the new version.
