### ISSUE TITLE
[BUG] LeaveTarget error with TargetModels

### ISSUE THREAD

**Issue by ZenVee** [qbcore-framework/qb-target#178]
**Describe the bug**
When viewing a target and the eye goes off the model/target there is an error and it sometimes breaks the third eye. Also while viewing the target from a distance the error is printed. 

https://i.imgur.com/d9FQump.png

**To Reproduce**
1. Stand at a distance from the model and open your third eye and look at the model that has the target.
or
1. Stand close to the target, view the target and move the third eye off the target and back onto it, sometimes it will error out.

**Expected behavior**
Well, if viewing from a distance it shouldn't indicate im looking at a target, and when closer to the target it should work as intended and not error out.

**Screenshots**
https://i.imgur.com/xzKaAeB.png

**Additional context**
Here is a video: https://youtu.be/sYA9MLP8PlI

**Comment by davoucci** [comment]
i have the same error

**Comment by Mustachedom** [comment]
same here

**Comment by RyuHiryu** [comment]
Yup I have the same error now, any assistance getting this resolved would be great

**Comment by Rosedrip** [comment]
hey everyone, to fix this issue please look at how your ensured scripts are setup, specifically make sure qb-core and qb-target are at the top and do not ensure ox_lib before qb-target, that is most likely why your having this problem. have a nice day!

**Comment by Rosedrip** [comment]
Update QB-target and ensure it before everything else right under qb-core
