### ISSUE TITLE
Don't use this

### ISSUE THREAD

**Issue by BerkieBb** [qbcore-framework/qb-target#186]
Use ox_target instead, it's a better alternative.

It may not have the ped spawner in here but it's faster and more accurate.

You can replace the ped spawner with ms-peds as linked in the README.md.

Thank you for reading this.

**Comment by BerkieBb** [comment]
As the author of this resource, you should listen to this.

**Comment by Sharkiiie** [comment]
Yeah fr, the guy that coded qb-target kinda sucks...

**Comment by ChatDisabled** [comment]
https://github.com/qbcore-framework/qb-target/assets/44729807/2a57b482-c562-4538-84aa-db6bf9f0cfd2

**Comment by tom-osborne** [comment]
> This issue has had 60 days of inactivity & will close within 7 days

Still relevant

**Comment by TonybynMp4** [comment]
> This issue has had 60 days of inactivity & will close within 7 days

still relevant

**Comment by jnccloud** [comment]
> This issue has had 60 days of inactivity & will close within 7 days

very relevant

**Comment by krrm1** [comment]
ops
