### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by REALNXT** [qbcore-framework/qb-target#188]
hi i'm searching for this target icon please
![image](https://github.com/qbcore-framework/qb-target/assets/110566680/f6f2b246-633f-4995-8bf6-9a176cf69d85)

**Comment by bryg** [comment]
Check out the Font Awesome Icons.
Open Storage: "fa-solid fa-box-open"
Buy a Storage: "fa-solid fa-boxes-stacked"
