### ISSUE TITLE
can't open options

### ISSUE THREAD

**Issue by macneko1016** [qbcore-framework/qb-target#190]
I'm using a car dealer script using qb-target, but I can't open the vehicle option that appears when buying a car.
Mouse cursor doesn't appear
![スクリーンショット (365)](https://github.com/qbcore-framework/qb-target/assets/130758143/2975a335-7151-4e41-95ab-be3b0aff99b1)

**Comment by Bennn3t** [comment]
@macneko1016 You will need to press the focus button (left-alt). Check your keybinds if it doesnt work.

**Comment by NietThijmen** [comment]
This is an issue of qb-menu, not qb-target
