### ISSUE TITLE
need a support for an issue 

### ISSUE THREAD

**Issue by oXTheGodFatherXo** [qbcore-framework/qb-target#194]
**Problem:**
peds multiply 

**Wanted Outcome:**
how to fix it

**Current Point:**
All information about where you are now with your problem goes here

**Screenshots:**
![image](https://github.com/qbcore-framework/qb-target/assets/154591279/d3b2d993-ad08-4160-bc07-208f8141e36f)

**Comment by QWSA21** [comment]
Same Problem

**Comment by Obtaizen** [comment]
How is your config set up, a friend of mine was having the same problem and it was due to the config not being correct?
