### ISSUE TITLE
[BUG] Font Awesome Eye Not Showing

### ISSUE THREAD

**Issue by snalye** [qbcore-framework/qb-target#195]
**Describe the bug**
For some of my players, the font awesome eye, far fa-eye, is not showing for them. When they reach an interactable area, the options show but the eye itself does not show.  However, for some players the eye does show up. Unsure if this is a font awesome issue, a client issue, or an issue with the latest FiveM build.

**To Reproduce**
1. Hold target keybind
2. Locate a target zone

**Expected behavior**
When holding the keybind, you should expect to see the font awesome eye.

**Screenshots**
[Player Video of it not working](https://medal.tv/games/gta-v/clips/1U3Wl6_LYtZZ18/d1337hasdSZO?invite=cr-MSxkVEssNjMwMDcxNzks)
[Player Video of it not working](https://clips.twitch.tv/WanderingSilkyMangetoutAllenHuhu-DPPZT4Qc2m7Lre-x)
[Player screenshot of it working](https://i.imgur.com/zX7nyO5.jpeg)
[New error since Feb 7th](https://media.discordapp.net/attachments/1205119776482140230/1205208851159326761/image.png)

**Additional context**
On the current version of qb-target.

**Comment by stefankent** [comment]
**Describe the bug**

I'll add to this, around 50% of our serverbase cannot view the third eye, as many have discussed on discord there have been no server changes and we haven't added or removed any files. It was working fine until today when we immediately started receiving reports from players. I can see there have been no changes to qb-target which makes it strange but with the amount of reports at least its now a common issue.


The third eye doesn't show but if you right click the target, it does still show its options.
 So at least the keybind is actually working
 


**To Reproduce**
Steps to reproduce the behavior:

Hold target keybind ALT
Locate a target zone eg. qb-atm

**Expected behavior**
When holding the keybind, you should expect to see the blue eye.



**Additional context**

I have personally reinstalled GTA
Reinstalled FiveM
Updated all windows drivers
Update graphics drivers

tested on PC Windows 10
tested on Laptop Windows 11

I confirmed far fa-eye icon is working from fontawesome
and replaced with other icons that i know do work to no avail
StandardEyeIcon: "far fa-eye",

I reinstalled a fresh qbcore on a test server

I visited other cities on fivem advertised as qbcore

The third eye just does not show

**Comment by timonation** [comment]
same issue here

**Comment by ihustle662** [comment]
same issue just started all of a sudden

**Comment by MALDWELL** [comment]
Assuming it is something within the font awesome import functionality. Any icon, free or not, does not work within qb-target. Fresh installed qb-target to no avail

**Comment by SwagDaddyBrad** [comment]
Having this issue as well!

**Comment by KK7130** [comment]
Having the same issue. Was working yesterday perfectly fine. Today me and multiple people on my server are having this issue and getting this error code;  SCRIPT ERROR: Error executing native 0xfcdff7b72d23a1ac at address FiveM_b2944_GTAProcess.exe+1611463. ; RaycastCamera^7 (^5@qb-target/client.lua^7:113). Not sure what it means or what would have caused it?

**Comment by ryuque** [comment]
The same thing happened on our server.

Here is the solution.
However, this solution is a guess based on experimentation.

In the Setting/Game/Update channel of the front page of Fivem
on the front page of Fivem is "Release" and Ver. 7424
and the channel is Ver. 7424.

On our server, when this problem occurred, we assumed that the cause of this problem was a failed download of Font Awesome.
Therefore, we localized Font Awesome, but this did not solve the problem.

We therefore concluded that the problem was caused by a different version of Fivem.

**Comment by ryuque** [comment]
If this does not cure the disease, it can only be due to the individual's environment.

However, we do not believe there are any technical problems with qb-target.
However, if this problem persists, the central fas fa-eye will need to be changed to something different.

**Comment by GhzGarage** [comment]
Can you try this and see if it resolves the issue? https://github.com/qbcore-framework/qb-target/pull/196

**Comment by snalye** [comment]
Will give it a try

**Comment by MALDWELL** [comment]
> Can you try this and see if it resolves the issue? #196

negative on this

**Comment by TKDubsta** [comment]
> > Can you try this and see if it resolves the issue? #196
> 
> negative on this

Hey, can you try replacing your fontawesome import on line 5 of index.html with this:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
```

**Comment by Wert22** [comment]
Hi, I was quite surprised when I encountered this problem, but I found something like this for a solution. You can try if you want.

Steps : 
- Open qb-target/html/js/app.js
- In data paramaters find TargetEyeStyleObject and display like mine below: Assign a "block" value

My photo : 

![image](https://github.com/qbcore-framework/qb-target/assets/83890612/73551002-0649-4827-80f0-236fb3cb13de)

Note: This works for me, you can give feedback by trying it, thank you.

**Comment by TKDubsta** [comment]
> Hi, I was quite surprised when I encountered this problem, but I found something like this for a solution. You can try if you want.
> 
> Steps :
> 
> * Open qb-target/html/js/app.js
> * In data paramaters find TargetEyeStyleObject and display like mine below: Assign a "block" value
> 
> My photo :
> 
> ![image](https://private-user-images.githubusercontent.com/83890612/303792103-73551002-0649-4827-80f0-236fb3cb13de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTg4NjIsIm5iZiI6MTcwNzUxODU2MiwicGF0aCI6Ii84Mzg5MDYxMi8zMDM3OTIxMDMtNzM1NTEwMDItMDY0OS00ODI3LTgwZjAtMjM2ZmIzY2IxM2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDIyNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YjA0NTYxODE1ZmJkNzFhODIxODZmZmNjY2U2YWQwNjU3MWM2OTI5ZDM4NDMyYjllZjM4MWMyZDdmNmRkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHRnIbeV-LBJ4ZDURPEl1N6rxvuGWL3v8gQt55hcCd4)
> 
> Note: This works for me, you can give feedback by trying it, thank you.

this is not the ideal fix as you are adding more load by not using v-show. Try implementing the change #196

**Comment by kathryn2101** [comment]
> Can you try this and see if it resolves the issue? #196

i did this and now get this error

![image](https://github.com/qbcore-framework/qb-target/assets/89110153/e65b9217-43b7-48f1-80cf-818eb722eb30)

**Comment by snalye** [comment]
> > Can you try this and see if it resolves the issue? #196
> 
> i did this and now get this error
> 
> ![image](https://private-user-images.githubusercontent.com/89110153/303795564-e65b9217-43b7-48f1-80cf-818eb722eb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MjA2MDQsIm5iZiI6MTcwNzUyMDMwNCwicGF0aCI6Ii84OTExMDE1My8zMDM3OTU1NjQtZTY1YjkyMTctNDNiNy00OGYxLTgwY2YtODE4ZWI3MjJlYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDIzMTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMzQxNGY2YmViNTNkOTAxYTk2MDIxMWRkZWM2ZWQ4NGZmY2YyY2JhYzM2M2MwZGZhYWEzMDFhMTgwNGFmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r8y_DFT-nXe74oy-6Qf1rl4QrXmkLPxPtgsRIWJOmFg)

I've got that error before and after the potential fix

**Comment by kathryn2101** [comment]
> > > Can you try this and see if it resolves the issue? #196
> > 
> > 
> > i did this and now get this error
> > ![image](https://private-user-images.githubusercontent.com/89110153/303795564-e65b9217-43b7-48f1-80cf-818eb722eb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MjA2MDQsIm5iZiI6MTcwNzUyMDMwNCwicGF0aCI6Ii84OTExMDE1My8zMDM3OTU1NjQtZTY1YjkyMTctNDNiNy00OGYxLTgwY2YtODE4ZWI3MjJlYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDIzMTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMzQxNGY2YmViNTNkOTAxYTk2MDIxMWRkZWM2ZWQ4NGZmY2YyY2JhYzM2M2MwZGZhYWEzMDFhMTgwNGFmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r8y_DFT-nXe74oy-6Qf1rl4QrXmkLPxPtgsRIWJOmFg)
> 
> I've got that error before and after the potential fix

Sorry ive only just noticed this issue not been very well past few days so just catching up now to the latest issue

**Comment by rivickys** [comment]
How to fix qb-target issue
goto qb-target/html/index.html

change the font awesome link to this one in line 15
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css

**Comment by Wert22** [comment]
> > Hi, I was quite surprised when I encountered this problem, but I found something like this for a solution. You can try if you want.
> > Steps :
> > 
> > * Open qb-target/html/js/app.js
> > * In data paramaters find TargetEyeStyleObject and display like mine below: Assign a "block" value
> > 
> > My photo :
> > ![image](https://private-user-images.githubusercontent.com/83890612/303792103-73551002-0649-4827-80f0-236fb3cb13de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTg4NjIsIm5iZiI6MTcwNzUxODU2MiwicGF0aCI6Ii84Mzg5MDYxMi8zMDM3OTIxMDMtNzM1NTEwMDItMDY0OS00ODI3LTgwZjAtMjM2ZmIzY2IxM2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDIyNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YjA0NTYxODE1ZmJkNzFhODIxODZmZmNjY2U2YWQwNjU3MWM2OTI5ZDM4NDMyYjllZjM4MWMyZDdmNmRkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHRnIbeV-LBJ4ZDURPEl1N6rxvuGWL3v8gQt55hcCd4)
> > Note: This works for me, you can give feedback by trying it, thank you.
> 
> this is not the ideal fix as you are adding more load by not using v-show. Try implementing the change #196

As I said, this is already a temporary method. It can be used in a temporary way until we solve it with a smoother method.

**Comment by snalye** [comment]
> How to fix qb-target issue goto qb-target/html/index.html
> 
> change the font awesome link to this one in line 15 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css

Line 15 is the Line Awesome link https://github.com/qbcore-framework/qb-target/blob/76bffd7937630933ffc15e070f0e8b5d2a28ba69/html/index.html#L15

Line 5 is the font awesome https://github.com/qbcore-framework/qb-target/blob/76bffd7937630933ffc15e070f0e8b5d2a28ba69/html/index.html#L5

**Comment by snalye** [comment]
Going to attempt to change the eye from `far fa-eye` to `las la-eye` and see what players say

https://github.com/qbcore-framework/qb-target/blob/76bffd7937630933ffc15e070f0e8b5d2a28ba69/html/js/app.js#L6

**Comment by snalye** [comment]
> Can you try this and see if it resolves the issue? #196

No change from this or from my icon change. Some of my players still do not see the eye.

Now getting a report that a player who previously did not have it, got it back after one of our server restarts but I did not push any changes until an hour ago.

**Comment by ryuque** [comment]
In the server at our place,
I have found people who have solved the problem by the following methods.

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
Match the game version to Release　
Ver. 7424

Delete (uninstall) all games from the folder

Download Fivem again.
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

On our server
https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
I have made changes so that I can use the fonts locally without having to download the　https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

However, this did not solve the problem, so it does not appear to be the cause of the failure to download the Font.

**Comment by MALDWELL** [comment]
> In the server at our place, I have found people who have solved the problem by the following methods.
> 
> ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー Match the game version to Release　 Ver. 7424
> 
> Delete (uninstall) all games from the folder
> 
> Download Fivem again. ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
> 
> On our server https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css I have made changes so that I can use the fonts locally without having to download the　https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
> 
> However, this did not solve the problem, so it does not appear to be the cause of the failure to download the Font.


Change your body in index.html to this


<body>
    <div id="target-wrapper">
        <q-icon id="target-eye" :name="CurrentIcon" v-if="Show" :style="TargetEyeStyleObject"></q-icon>
        <div id="target-label-wrapper">
            <div id="target-label"></div>
        </div>
    </div>
</body>

It's a temp fix we devised in the discord today that alleviated my issues

**Comment by TKDubsta** [comment]
> How to fix qb-target issue goto qb-target/html/index.html
> 
> change the font awesome link to this one in line 15 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css

this is not correct.

**Comment by TKDubsta** [comment]
> > In the server at our place, I have found people who have solved the problem by the following methods.
> > ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー Match the game version to Release　 Ver. 7424
> > Delete (uninstall) all games from the folder
> > Download Fivem again. ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
> > On our server https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css I have made changes so that I can use the fonts locally without having to download the　https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
> > However, this did not solve the problem, so it does not appear to be the cause of the failure to download the Font.
> 
> Change your body in index.html to this
> 
> ```
> <body>
>     <div id="target-wrapper">
>         <q-icon id="target-eye" :name="CurrentIcon" v-if="Show" :style="TargetEyeStyleObject"></q-icon>
>         <div id="target-label-wrapper">
>             <div id="target-label"></div>
>         </div>
>     </div>
> </body>
> ```
> 
> It's a temp fix we devised in the discord today that alleviated my issues

to confirm, this is pull request #196 

We are working on a different long term solition however this fixes it for now.

**Comment by snalye** [comment]
> > In the server at our place, I have found people who have solved the problem by the following methods.
> > ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー Match the game version to Release　 Ver. 7424
> > Delete (uninstall) all games from the folder
> > Download Fivem again. ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
> > On our server https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css I have made changes so that I can use the fonts locally without having to download the　https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
> > However, this did not solve the problem, so it does not appear to be the cause of the failure to download the Font.
> 
> Change your body in index.html to this
> 
> ```
> <body>
>     <div id="target-wrapper">
>         <q-icon id="target-eye" :name="CurrentIcon" v-if="Show" :style="TargetEyeStyleObject"></q-icon>
>         <div id="target-label-wrapper">
>             <div id="target-label"></div>
>         </div>
>     </div>
> </body>
> ```
> 
> It's a temp fix we devised in the discord today that alleviated my issues

Will attempt this but won't have any results until tomorrow.

**Comment by snalye** [comment]
Fixed with https://github.com/qbcore-framework/qb-target/issues/195
