### ISSUE TITLE
[BUG] Error spam latest update

### ISSUE THREAD

**Issue by jamazzz** [qbcore-framework/qb-target#198]
**Describe the bug**
If a user is using the latest version of qb-target it spams the client console (tested in the latest FiveM version)

**To Reproduce**
1. Go to 'Use target in-game'
2. Open F8'

**Expected behavior**
The same error should pop up multiple times 

**Screenshots**
![image](https://github.com/qbcore-framework/qb-target/assets/114000467/07808b3b-9cd5-433a-a61e-f0dd3a2ce844)

**Comment by GhzGarage** [comment]
[0x9f47b058362c84b5](https://docs.fivem.net/natives/?_0x9F47B058362C84B5)

**Comment by jamazzz** [comment]
I wasn't looking at any object probably missing a check to check if a user is looking at a object or just air.

**Comment by Borreke0** [comment]
Having the same issue..

**Comment by derTweaky** [comment]
Yes

**Comment by rapeurtueur** [comment]
Same issues

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-target/commit/ea654b7692657b915e29380dfa991e1ac136bce8

**Comment by GilesKysel** [comment]
Having the same issue..

**Comment by Borreke0** [comment]
> Having the same issue..

Do the last commit and its fixed. :)
