### ISSUE TITLE
[BUG]Unsupported Operation

### ISSUE THREAD

**Issue by ChrisNewmanDev** [qbcore-framework/qb-target#201]
**Describe the bug**
I keep getting this error when 3rd eyeing. Any assistance would greatly be appreciated. 

**To Reproduce**

**Expected behavior**
I keep getting this error when 3rd eyeing. Any assistance would greatly be appreciated. 

**Screenshots**

**Additional context**
![11212](https://github.com/qbcore-framework/qb-target/assets/150890840/60accc06-2c13-4bbf-a307-b0e89e2424af)

**Comment by ChrisNewmanVortex** [comment]
Meant to make a help needed ticket.

**Comment by parkzinc** [comment]
same problem
