### ISSUE TITLE
[BUG] Error executing native

### ISSUE THREAD

**Issue by rxnm** [qbcore-framework/qb-target#202]
**Describe the bug**
Since updating to the latest qb-target I am getting this error sometimes when I try to use the target on something, it doesn't happen always though, it is kind of on and off. 

**Expected behavior**
How it is meant to work as intended and how it worked well before, it still works well but just spams these errors from time to time.

**Screenshots**
![Screenshot_1](https://github.com/qbcore-framework/qb-target/assets/2183651/5ff7e132-d748-4297-9dcc-cfe418605bce)

**Comment by Roydeking52** [comment]
I have the same problem i get that native error with the new version off qb-truckrobbery.

**Comment by bo0tych33ks** [comment]
Same issue with other scrips but only on certain things and my server.cfg is loading qb-target before any other scripts so its not that

**Comment by Realturnpoint** [comment]
i have the same issue recently i switched to the new one

**Comment by EmZ44** [comment]
Also got the same issue

**Comment by rxnm** [comment]
Still no fix for this? it was reported originally by me in March.

**Comment by rxnm** [comment]
I fixed it, line 119 I changed this:

`entityHit = HasEntityClearLosToEntity(entityHit, playerPed, 7) and entityHit`

To this:

`entityHit = GetEntityPlayerIsFreeAimingAt(PlayerId(entityHit, playerPed, 7)) and entityHit`

Now it works fine. It seem that it broke around game version 3095.

**Comment by telmoalves123123** [comment]
> I fixed it, line 119 I changed this:
> 
> `entityHit = HasEntityClearLosToEntity(entityHit, playerPed, 7) and entityHit`
> 
> To this:
> 
> `entityHit = GetEntityPlayerIsFreeAimingAt(PlayerId(entityHit, playerPed, 7)) and entityHit`
> 
> Now it works fine. It seem that it broke around game version 3095.

WORKED FOR ME !! TY

**Comment by rxnm** [comment]
> I fixed it, line 119 I changed this:
> 
> `entityHit = HasEntityClearLosToEntity(entityHit, playerPed, 7) and entityHit`
> 
> To this:
> 
> `entityHit = GetEntityPlayerIsFreeAimingAt(PlayerId(entityHit, playerPed, 7)) and entityHit`
> 
> Now it works fine. It seem that it broke around game version 3095.

This does fix the error, but I just realized that it also breaks the usage of the ATMs at Fleeca on (Vespucci Boulevard). So a propper fix is still needed.

**Comment by GhzGarage** [comment]
Duplicate issue https://github.com/qbcore-framework/qb-target/issues/210
