### ISSUE TITLE
Im getting an error 

### ISSUE THREAD

**Issue by patrioticpsycho** [qbcore-framework/qb-target#205]
**Describe the bug**
I get a error saying attempted to index a nil value (field) when I'm trying to click on something I was fixing cords everything was working did a few restarts and it gave me a native error and then went from that to this error and as of yesterday it's still giving it me but will check again we I get home from work as I have scheduled restarts to see if it fixed it's self 
![Screenshot_20240625_072254_Discord](https://github.com/qbcore-framework/qb-target/assets/150745197/0c6c153a-04d5-4cae-8c52-fa6233dcec5b)
![Screenshot_20240625_072246_Discord](https://github.com/qbcore-framework/qb-target/assets/150745197/63e81585-28ad-4854-be30-64b1a4638c36)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by patrioticpsycho** [comment]
Is this about my server not sure what ur talking about

**Comment by GhzGarage** [comment]
Duplicate issue https://github.com/qbcore-framework/qb-target/issues/210
