### ISSUE TITLE
[SUPPORT] A lot of scripts show an error

### ISSUE THREAD

**Issue by Ninovui** [qbcore-framework/qb-target#206]
**Problem:**
We are trying an issue where NPCS doesn't spawn correctly on our server. A lot of scripts shows the error "@qb-target/client.lua:467: attempt to index a nil value (global 'BoxZone')

**Wanted Outcome:**
Make the other plugins work with qu-target

**Current Point:**
We do not find anything about troubleshooting this issue

**Screenshots:**
https://imgur.com/a/qP01gnt + https://imgur.com/a/DnMibCV

**Additional context:**
Problem occured after we tried to add plugins that makes peds spawn

**Comment by GhzGarage** [comment]
install PolyZone
